language: python

branches:
  only:
    - master

python:
  - "3.6"
env:
  - PYTORCH_VERSION=master
  - PYTORCH_VERSION=stable
  - PYTORCH_VERSION=stable WITH_PYRO=true
  - PYTORCH_VERSION=stable WITH_PYRO=true EXAMPLES=true

install:
  - pip install numpy; pip install scipy; pip install scikit-learn;
  - if [[ $PYTORCH_VERSION = "master" ]]; then
      pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
      python setup.py build develop;
    else
      pip install torch==1.6+cpu -f https://download.pytorch.org/whl/torch_stable.html;
    fi
  - if [[ $WITH_PYRO == true ]]; then
      pip install git+https://github.com/pyro-ppl/pyro@dev;
    fi
  - if [[ $EXAMPLES == true ]]; then
      pip install pytest nbval jupyter tqdm matplotlib torchvision scipy;
    fi

script:
  - python -c "import torch; print('PyTorch Version:', torch.__version__)"
  - if [[ $EXAMPLES == true ]]; then
      python setup.py build develop;
      grep -l smoke_test examples/**/*.ipynb | xargs grep -L 'smoke_test = False' | CI=true xargs pytest --nbval-lax --current-env;
    else
      python -m unittest discover;
    fi

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8==3.7.9 flake8-print==3.1.4
      script: flake8
    - env: PRECOMMIT_CHECK
      python: "3.6"
      install: pip install pre-commit; pre-commit install; pre-commit run seed-isort-config || true
      script: SKIP=flake8 pre-commit run --files test/**/*.py gpytorch/**/*.py
    - env: DOCS_CHECK
      addons:
        apt_packages:
          - pandoc
      python: "3.6"
      install: pip install "nbformat<=4.4" IPython ipykernel "sphinx<3.0.0" sphinx_rtd_theme nbsphinx m2r attrs==19.1 scipy
      script: python setup.py build_sphinx
