language: python

branches:
  only:
    - master

python:
  - "3.6"
env:
  - PYTORCH_VERSION=master
  - PYTORCH_VERSION=stable
  - PYTORCH_VERSION=stable WITH_PYRO=true

install:
  - if [[ $PYTORCH_VERSION = "master" ]]; then
      pip install numpy;
      pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
      python setup.py build develop;
    else
      pip install torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html;
    fi
  - if [[ $WITH_PYRO == true ]]; then
      pip install pyro-ppl;
    fi

script:
  - python -c "import torch; print('PyTorch Version:', torch.__version__)"
  - python -m unittest discover

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 flake8-print
      script: flake8
    - env: DOCS_CHECK
      addons:
        apt_packages:
          - pandoc
      python: "3.6"
      install: pip install IPython ipykernel sphinx sphinx_rtd_theme nbsphinx m2r attrs==19.1
      script: python setup.py build_sphinx
