# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package to PyPI and Anaconda

on:
  release:
    types: [created]

jobs:
  run_test_suite:
    uses: ./.github/workflows/run_test_suite.yml

  deploy_pypi:
    runs-on: ubuntu-latest
    needs: run_test_suite
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools_scm setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m setuptools_scm
        python setup.py sdist bdist_wheel
        twine upload dist/*

  deploy_conda:
    runs-on: ubuntu-latest
    needs: run_test_suite
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        python-version: "3.8"
    - name: Install dependencies
      run: |
        conda install -y anaconda-client conda-build
        conda install linear_operator -c gpytorch
        pip install setuptools_scm
    - name: Build and publish
      run: |
        conda config --set anaconda_upload yes
        conda config --append channels pytorch
        conda config --append channels gpytorch
        /usr/share/miniconda/bin/anaconda login --username ${{ secrets.CONDA_USERNAME }} --password ${{ secrets.CONDA_PASSWORD }}
        python -m setuptools_scm
        cd .conda
        conda build .
        /usr/share/miniconda/bin/anaconda logout
        cd ..
